env:
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
rules:
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  import/extensions: [, { "js": "always", "json": "never" }]
plugins:
  - jest